name: 'dbt_transform'
version: '1.0.0'


profile: 'dbt_transform'

model-paths: ["src/dbt_transform/models"]
test-paths: ["src/dbt_transform/tests"]
seed-paths: ["data/preprocessed"]

models:
  dbt_transform:
    staging:
      +materialized: view
      +schema: staging
    warehouse:
      +materialized: view
      +schema: warehouse
    marts:
      +materialized: table
      +schema: marts