name: 'WMCSRP2_dataset'
version: '1.0.0'

profile: 'main'

model-paths: ["models"]
test-paths: ["tests"]

models:
  WMCSRP2_dataset:
    raw:
      +materialized: view
      +schema: raw
    warehouse:
      +materialized: view
      +schema: warehouse
    marts:
      +materialized: table
      +schema: marts