name: 'WMCSRP2_dataset'
version: '1.0.0'

profile: 'main'

model-paths: ["models"]
test-paths: ["tests"]

models:
  WMCSRP2_dataset:
    staging:
      +materialized: view
      +schema: staging
    warehouse:
      +materialized: view
      +schema: warehouse
    marts:
      +quoting:
        identifier: true
      +materialized: "{{ 'view' if target.type == 'duckdb' else 'table' }}"
      +schema: marts