
main:
  
  target: remote

  outputs:

    local:
      type: duckdb
      path: WMCSRP2.duckdb
      schema: md
      threads: 4

    remote:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASS') }}"
      port: 25060
      dbname: wmcsrp2
      schema: public

