
main:
  
  target: "{{ env_var('DATA_BACKEND') }}"

  outputs:

    duckdb:
      type: duckdb
      path: wmcsrp2.duckdb
      extensions:
        - parquet
        - httpfs
      schema: public

    postgres:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASS') }}"
      port: 25060
      dbname: wmcsrp2
      schema: public

