
main:
  
  target: remote

  outputs:

    local:
      type: duckdb
      path: WMCSRP2.duckdb
      schema: md
      threads: 4

    remote:
      type: postgres
      host: cwc-db-2-do-user-15270656-0.l.db.ondigitalocean.com
      user: doadmin
      pass: "{{ env_var('WMCSRP_DB_PASS') }}"
      port: 25060
      dbname: wmcsrp2
      schema: public

