select
    lad23cd,
    case
        when participation_type = 'Adult engagement with the arts in the last 12 months (physical) (Tables A2 to A14 and A16 to A26), April 2023 to March 2024' 
            then 'Engaged with the arts physically (attended an event or participated in an activity in person) in the last 12 months [r] [Note 30]'
        when participation_type = 'Adult engagement with written, practiced or performed music, April 2023 to March 2024' 
            then 'Written, practiced or performed music'
        when participation_type = 'Adult engagement with watching TV programmes live at the time they were broadcast, May 2023 to March 2024' 
            then 'Watched TV programmes live at the time they were broadcast'
        when participation_type = 'Adult engagement with painting, drawing, printmaking, calligraphy, colouring, April 2023 to March 2024' 
            then 'Did painting, drawing, printmaking, calligraphy, colouring'
        when participation_type = 'Adult engagement with made films or videos including original video content and animations, April 2023 to March 2024' 
            then 'Made films or videos including original video content and animations'
        when participation_type = 'Adult engagement with some other cultural event in England, April 2023 to March 2024' 
            then 'Attended some other cultural event in England'
        when participation_type = 'Adult engagement with an arts festival or carnival, April 2023 to March 2024' 
            then 'Attended an arts festival or carnival'
        when participation_type = 'Adult engagement with watching a pre-recorded music or dance event, April 2023 to March 2024' 
            then 'Watched a pre-recorded music or dance event'
        when participation_type = 'Adult engagement with reading news in a printed newspaper, April 2023 to March 2024' 
            then 'Read news in a printed newspaper'
        when participation_type = 'Adult engagement with watching a pre-recorded arts event including theatre, visual arts or literature, April 2023 to March 2024' 
            then 'Watched a pre-recorded arts event including theatre, visual arts or literature'
        when participation_type = 'Adult engagement with other arts, crafts, or creative activities, April 2023 to March 2024' 
            then 'Did other arts, crafts, or creative activities in person'
        when participation_type = 'Adult engagement with an event connected with literature, books, reading, poetry reading or writing, April 2023 to March 2024' 
            then 'Attended an event connected with literature, books, reading, poetry reading or writing'
        when participation_type = 'Adult engagement with reading an e-book or e-magazine, April 2023 to March 2024' 
            then 'Read an e-book or e-magazine'
        when participation_type = 'Adult engagement with a craft exhibition, April 2023 to March 2024' 
            then 'Attended a craft exhibition'
        when participation_type = 'Adult engagement with an in-person esports contest or video game competition event, May 2023 to March 2024' 
            then 'Attended an in-person esports contest or video game competition event'
        when participation_type = 'Adult engagement with crafts (textile, sewing, ceramic, sculpting, carving, woodwork), April 2023 to March 2024' 
            then 'Did crafts (textile, sewing, ceramic, sculpting, carving, woodwork)'
        when participation_type = 'Adult engagement with a live dance event, April 2023 to March 2024' 
            then 'Attended a live dance event'
        when participation_type = 'Adult engagement with an exhibition of art, photography or sculptures, April 2023 to March 2024' 
            then 'Attended an exhibition of art, photography or sculptures'
        when participation_type = 'Adult engagement with reading news online from a national or local news publisher, May 2023 to March 2024' 
            then 'Read news online from a national or local news publisher'
        when participation_type = 'Adult engagement with written stories, plays, or poetry, April 2023 to March 2024' 
            then 'Written stories, plays, or poetry'
        when participation_type = 'Adult engagement with playing video games including on a smartphone or tablet, May 2023 to March 2024' 
            then 'Played video games including on a smartphone or tablet'
        when participation_type = 'Adult engagement with a street art event, April 2023 to March 2024' 
            then 'Attended a street art event'
        when participation_type = 'Adult engagement with a live music event, April 2023 to March 2024' 
            then 'Attended a live music event'
        when participation_type = 'Adult engagement with watching TV programmes using a streaming service, May 2023 to March 2024' 
            then 'Watched TV programmes using a streaming service'
        when participation_type = 'Adult engagement with watching films live at the time they were broadcast, May 2023 to March 2024' 
            then 'Watched films live at the time they were broadcast'
        when participation_type = 'Adult engagement with a cinema screening of a film or movie in the last 12 months, April 2023 to March 2024' 
            then 'Attended a cinema screening of a film or movie'
        when participation_type = 'Adult engagement with reading books, graphic novels or magazines, April 2023 to March 2024' 
            then 'Read books, graphic novels or magazines in the last 12 months'
        when participation_type = 'Adult engagement with a comedy event, April 2023 to March 2024' 
            then 'Attended a comedy event'
        when participation_type = 'Adult engagement with listening to live radio online through a computer, laptop, tablet or phone, April 2023 to March 2024' 
            then 'Listened to live radio online through a computer, laptop, tablet or phone'
        when participation_type = 'Adult engagement with a fashion show, April 2023 to March 2024' 
            then 'Attended a fashion show'
        when participation_type = 'Adult engagement with watching a live arts event including theatre, visual arts or literature online, April 2023 to March 2024' 
            then 'Watched a live arts event including theatre, visual arts or literature online'
        when participation_type = 'Adult engagement with a theatre play, drama, musical, pantomime, ballet or opera, April 2023 to March 2024' 
            then 'Attended a theatre play, drama, musical, pantomime, ballet or opera'
        when participation_type = 'Adult engagement with photography as a hobby, April 2023 to March 2024' 
            then 'Did photography as a hobby'
        when participation_type = 'Adult engagement with listening to an audiobook, April 2023 to March 2024' 
            then 'Listened to an audiobook'
        when participation_type = 'Adult engagement with listening to downloaded music, April 2023 to March 2024' 
            then 'Listened to downloaded music'
        when participation_type = 'Adult engagement with designed or programmed video games including on a smartphone or tablet, April 2023 to March 2024' 
            then 'Designed or programmed video games including on a smartphone or tablet'
        when participation_type = 'Adult engagement with watching a live music or dance event, watched as it was happening, April 2023 to March 2024' 
            then 'Watched a live music or dance event, watched as it was happening'
        when participation_type = 'Adult engagement with choreographed or performed a drama or dance routine, April 2023 to March 2024' 
            then 'Choreographed or performed a drama or dance routine'
        when participation_type = 'Adult engagement with watching films using a streaming service, May 2023 to March 2024' 
            then 'Watched films using a streaming service'
        when participation_type = 'Adult engagement with listening to a podcast, April 2023 to March 2024' 
            then 'Listened to a podcast'
        when participation_type = 'Adult engagement with listening to streamed music, April 2023 to March 2024' 
            then 'Listened to streamed music'
        when participation_type = 'Adults who have not attended any events, April 2023 to March 2024' 
            then 'Attended Cultural Events in Person'
        when participation_type = 'Adults who have not participated, April 2023 to March 2024'
            then 'Participated in Creative Activities'
        when participation_type = 'Adult engagement with the arts in the last 12 months (digital) (Tables B2 to B13 and B15 to B18), April 2023 to March 2024'
            then 'Engaged Online with Culture and Arts'
        else participation_type
    end as participation_type,
    demographic,
    value,
    margin_of_error
from
    {{ ref('stg__modelled_participation_statistics') }}