name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate dbt Docs
        env:
          DATA_BACKEND: ${{ secrets.DATA_BACKEND }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
        run: dbt docs generate

      - name: Move docs to docs/ folder
        run: |
          rm -rf docs
          mv target docs

      - name: Commit and push updated docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Add docs folder changes
          git add docs
          # Only commit if there are changes
          if ! git diff-index --quiet HEAD --; then
              git commit -m "Update dbt docs [skip ci]"
              git push
          else
              echo "No changes to commit."
          fi